### ISSUE TITLE
Windows version detected as a virus/threat by windows defender

### ISSUE THREAD

**Issue by Tidominer** [Gentleflow/Airclap#2]
![image](https://github.com/Gentleflow/Airclap/assets/75866836/39d3ef59-d1cb-42ca-95e0-4717c31ecd09)
Windows defender identifies windows installer file from releases page as a virus. Here is VirusTotal scan:
https://www.virustotal.com/gui/file/09dbff845857fcaeffc4e3eba8cf8df018090261b93d64b065bf6e180ee8d8d7

**Comment by LiangLuDev** [comment]
Thank you very much for your feedback. First of all, it can be confirmed that Airclap does not have any virus-related issues. The current assumption is that the problem may be due to a lack of set packaging certificates. We will investigate further and resolve it. Thank you again.
